# -*- coding: utf-8 -*-
"""lista_exercicio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUTj2XBiouCdztrEoFKpiEaXuSumHzxX

**LISTA DE EXERCÍCIOS**

EXERCÍCIO 1 - FAÇA UM SCRIPT VERIFIQUE SE UM NÚMERO (*num*) É PAR OU IMPAR:
"""

import random
num = random.randint(1, 100)

print(num)

# SEU CODIGO AQUI ...

"""EXERCÍCIO 2 - FAÇA UMA SCRIPT QUE CALCULA UMA EXPRESSÃO MATEMÁTICA DADO 2 INTEIROS (*num1, num2 e op*) E UM OPERADOR (String = '+', '-', '*', '/'):"""

import random
num1 = random.randint(0, 100)
num2 = random.randint(0, 100)
op = ['+', '-', '*', '/'][random.randint(0, 3)]

print(num1, num2, op)

# SEU CODIGO AQUI ...

"""EXERCÍCIO 3 - FAÇA UM SCRIPT QUE IDENTIFIQUE SE UM NÚMERO INTEIRO (*num*) É PRIMO OU NÃO"""

import random
num = random.randint(1, 100)

print(num)

# SEU CODIGO AQUI ...

"""EXERCÍCIO 4 - FAÇA UM SCRIPT QUER RETORNE DE UMA LISTA DE INTEIROS (*lista*):

*   MAIOR ELEMENTO
*   MENOR ELEMENTO
*   TAMANHO

**DESAFIO:** NÃO USE FUNÇÕES *min(), max() e len()*!
"""

import random

lista = [random.randint(0,10) for i in range(5)]

print(lista)

# SEU CODIGO AQUI ...

"""EXERCÍCIO 5 - FAÇA UM SCRIPT QUE RETORNE DE UMA LISTA DE INTEIROS (*lista*):

* A MEDIA
* A MEDIANA
* A MODA
"""

import random

lista = [random.randint(0,10) for i in range(5)]

print(lista)

# SEU CODIGO AQUI ...

"""EXERCÍCIO 6 - FAÇA UMA FUNÇÃO QUE TENHA COMO ENTRADA UMA LISTA DE INTEIROS (*idades*) E RETORNE UMA LISTA COM AS FAIXAS DE CADA IDADE, DE ACORDO COM AS REGRAS A SEGUIR:<br>
* '<18', 
* '18 A 21', 
* '21 A 27', 
* '28 A 35', 
* '36 A 50', 
* '50 A 65', 
* '65+'
"""

import random

idades = [random.randint(5, 95) for i in range(100)]

print(idades)

# SEU CODIGO AQUI ...

"""EXERCÍCIO 7 - DADA UM LISTA (*cabecalho*) CONTENDO O CABEÇALHO DE UMA TABELA, FAÇA AS SEGUINTES TRANSFORMAÇÕES:<br>
* Remova espaços a direita e a esquerda (função \<string\>.strip())
* Deixe todas a letras maiúsculas (função \<string\>.upper())
* substitua " " (espaços) por "_" (função \<string\>.replace())
"""

cabecalho = ["nome ", "IdadE", "data de nascimento", "endereco", " cpf", "Valor Devido", "Valor ja pago"]


# SEU CODIGO AQUI ...